[versions]
junit = "6.0.2"
kotlin = "2.2.0"

[libraries]
assertk = { module = "com.willowtreeapps.assertk:assertk", version = "0.28.1" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }

[plugins]
agp = { id = "com.android.application", version = "8.13.0" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "6.0.7" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version = "0.5.0" }
detekt = { id = "dev.detekt", version = "2.0.0-alpha.1" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
publishReport = { id = "io.github.gmazzo.publications.report", version = "1.3.3" }
